### ISSUE TITLE
Cannot run the model

### ISSUE THREAD

**Issue by glciampaglia** [tambu85/misinfo_spread#1]
I have tried to follow the instructions in the README file but I could not get the model to run. I have set `num_iterations = 2` in `hoax_spread_main.R`, I have created the plots and results folder, and then I did the following:

```
> setwd(".")
> source("./hoax_spread_main.R")
[1] 1
Error in file(filename, "r", encoding = encoding) : 
  cannot open the connection
In addition: Warning message:
In file(filename, "r", encoding = encoding) :
  cannot open file 'fun_create_graph_with_gul_sk.R': No such file or directory
> 
```

Are you sure you included all files?

Also, can you please give more meaningful names to the files? From what I understood in the README the script that needed to be launched was `spreading_hoax.R` but it seems instead that the one that runs the simulation is `hoax_spread_main.R`. You could call the files with the functions of the model `model_functions.R` and the script with the parameter declarations `launch_simulation.R`.

Thanks!

**Comment by tambu85** [comment]
Azz mi sa che allora ho caricato uno dei file sbagliati! Ora sono in treno,
quando arrivo a casa controllo!
Il 25/Ott/2015 21:37, "Giovanni Luca Ciampaglia" <notifications@github.com>
ha scritto:

**Comment by tambu85** [comment]
Thanks, I forgot to upload the file with the function to create the network with the two communities.  Now I uploaded it and I changed its name too.  Moreover, I modified the name of the script to launch,  and I corrected it in the README (that was wrong). Please look if now it is ok!

**Comment by glciampaglia** [comment]
Thanks, it works!
